{% set name = "lbadmin" %}
{% set version = "0.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbAdmin-{{ version }}.tar.gz
  sha256: 89816c2efabb8dd4830c70f67f91cc662e30033bf8df37c7f0b2809885f0e23b

build:
  number: 0
  noarch: python
  entry_points:
    - lb-release-rpm=LbAdmin.RpmRelease:release
    - lb-resync-meta-info-repos=LbAdmin.RpmRelease:resync
    - lb-deployment-updatesdb=LbAdmin.LbDeploymentUpdateSdb:main
    - lb-create-one-lcg-meta-spec=LbAdmin.CreateLHCbLCGMetaSpec:main
    - lb-create-all-lcg-meta-specs=LbAdmin.CreateAllSpecs:main
    - lb-export-project-info=LbAdmin.ProjectDataExporter:export
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - nose >=1.0
    - pip
    - python <4.0
    - setuptools_scm
  run:
    - lbcommon
    - lbinstall
    - lbsoftconfdb2clients
    - python <4.0
    - six

test:
  imports:
    - LbAdmin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/LbAdmin
  summary: Administration tools for the LHCb environment and software
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
    - chrisburr
